### ISSUE TITLE
Request improvements to the Image Tool

### ISSUE THREAD

**Issue by fushi002** [ZQF-ReVN/RxValkyria#5]
Hello
First of all, thank you for the numerous useful tools you have made
Recently, I tried to translate it with the Valkyria tool you made, and it had good results.
Thank you again for taking this opportunity.
But I still need a little more help with the image translation

The MG2.py tool is useful for converting image files to MG2 files
The extraction tool can be used with Garbro.

But what you tested to create the MG2.py tool,
https://vndb.org/v44188
Games released after the above work, unfortunately, cannot extract images normally with Garbro tools

Specifically,
https://vndb.org/v46784
https://vndb.org/v48766
These are the two works above.

When you have time, I would like you to add a function so that the image is extracted normally.

Additionally, there's an extension type called am2,
It's probably multiple image files that are organized within one archive (mainly title directing files)
I'd also like you to implement a tool for this type of extension

Thank you for always making good tools
I wish you happiness.

**Comment by Dir-A** [comment]
I'm busy these days.
Let's ask @Cosetto first. ：Do you have any ideas?

**Comment by Cosetto** [comment]
Try this one
[ValkyriaTool.zip](https://github.com/Dir-A/Valkyria_Tools/files/15091094/ValkyriaTool.zip)

**Comment by fushi002** [comment]
> Try this one [ValkyriaTool.zip](https://github.com/Dir-A/Valkyria_Tools/files/15091094/ValkyriaTool.zip)

This tool has exactly the same functionality as mg2.py.
For this reason, it can only convert PNG files to MG2, and cannot convert newer MG2 files to PNG files.

**Comment by fushi002** [comment]
If you're busy, please add the feature when you have more time. 
I'll wait patiently. :)

**Comment by Dir-A** [comment]
I solved this problem, it uses a new encryption method
I opened a pr in here https://github.com/crskycode/GARbro/pull/53
now you can use the ci auto-build version to extract mg2 images before this pr merged
[GARbro-Mod-ci-build.zip](https://github.com/user-attachments/files/17197384/GARbro-Mod-ci-build.zip)

after extract image by garbro you can still use Cosetto's script to convert png to mg2, 
because the engine is still compatible with old format.

**Comment by fushi002** [comment]
Hello,

Thank you so much for not forgetting and updating the tool even after all this time.
I tested it, and it works perfectly.
I wish you nothing but the best in all that you do.
