### ISSUE TITLE
封包后出现了乱码

### ISSUE THREAD

**Issue by kithy233** [ZQF-ReVN/RxValkyria#6]
我最近在使用您的rxValkyria工具在修改封包之后，游戏运行出现了如下所示的乱码。又将原文件解包封包之后拖进根目录，可以正常运行，所以应该不是封包的问题。改动内容也只有解包出的json文件里的文本内容。搜索相关情况个人认为是最后游戏运行时没有使用GBK而是进行了不正常的SJIS解码。
于是使用le转区但是并没有解决问题。后来想到原汉化为繁中，于是转到繁中区，结果游戏无法运行。和电脑系统时间日中繁中排列组合后还是存在问题。后来看了您的视频后又尝试emeditor直接将json文件转码，排列组合后要么一开始就会提示转码后会有字符缺失，要么最后游戏无法运行。也按照某吧内的方法尝试删除或重新安装字体也没有解决。
所以请问一下还有没有其他的解决方法或者您在哪个视频内提到过相关信息，万分感谢。
![A]7QF5G8]R_~BF)[Z@OKV(S.png](https://github.com/user-attachments/assets/c571ad17-dcc3-4eff-a3a9-8889a67972af)

**Comment by Dir-A** [comment]
1、确保使用gbk导入文本（cp936）
2、在exe里搜索字符串，jpn，改成chs

**Comment by kithy233** [comment]
第二点可以稍微具体一点嘛，麻烦您了

**Comment by Dir-A** [comment]
![QQ20240728-232952](https://github.com/user-attachments/assets/817ba4e6-4433-4b99-927e-f704909c260c)
![QQ20240728-233056](https://github.com/user-attachments/assets/319af0dc-43c3-41ba-9c67-9c02048bba3b)
![QQ20240728-233127](https://github.com/user-attachments/assets/ca806d14-d8d1-4da7-b8f4-913cdf9372a2)
![QQ20240728-233153](https://github.com/user-attachments/assets/16be8328-66fd-4d60-8e7d-9a308e90ae9f)

**Comment by kithy233** [comment]
解决了，真的十分感谢
