### ISSUE TITLE
SDT_TextEditor没法导出文本

### ISSUE THREAD

**Issue by NooAcc** [ZQF-ReVN/RxValkyria#7]
### 1、使用 `Valkyria_DAT_Editor` 处理dat文件
```PowerShell
D:\Valkyria-Tools-x64-Release> .\Valkyria_DAT_Editor.exe -mode unpack -dat data06-00.dat -dir data06/
success! -> data06-00.dat
```

### 3、使用 `Valkyria_SDT_TextEditor`处理sdt文件夹
```PowerShell
D:\Valkyria-Tools-x64-Release> .\Valkyria_SDT_TextEditor.exe -mode batch -way export -sdt sdt/ -json sdt_json/ -code 932
export -> sdt/seen0000.sdt | not find text
export -> sdt/seen0001.sdt | not find text
export -> sdt/seen0002.sdt | not find text
export -> sdt/seen0003.sdt | not find text
export -> sdt/seen0004.sdt | not find text
export -> sdt/seen0005.sdt | not find text
export -> sdt/seen0010.sdt | not find text
export -> sdt/seen0011.sdt | not find text
export -> sdt/seen0012.sdt | not find text
export -> sdt/seen0013.sdt | not find text
export -> sdt/seen0014.sdt | not find text
export -> sdt/seen0015.sdt | not find text
export -> sdt/seen0016.sdt | not find text
export -> sdt/seen0020.sdt | not find text
export -> sdt/seen0021.sdt | not find text
export -> sdt/seen0022.sdt | not find text
export -> sdt/seen0023.sdt | not find text
export -> sdt/seen0024.sdt | sav -> sdt_json/seen0024.json
```

### 4、查看 `sdt_json`文件夹
里面只有一个 `seen0024.json` 文件，这显然不太对劲。
 `seen0024.json` 文件内容：
```JSON
[
	[
		{
			"org": "ビッチシステム・肌色変更・射精カウント",
			"tra": "ビッチシステム・肌色変更・射精カウント"
		}
	],
	[
		0
	]
]
```

### 1、删掉提示 `not find text` 的文件
```PowerShell
D:\Valkyria-Tools-x64-Release> .\Valkyria_SDT_TextEditor.exe -mode batch -way export -sdt sdt/ -json sdt_json/ -code 932
export -> sdt/seen0024.sdt | sav -> sdt_json/seen0024.json
```
结果和之前没啥太大的变化，仍然只有 `seen0024.json` 这个文件。

### 2、单独对 `seen0024.sdt` 文件进行提取
```PowerShell
D:\Valkyria-Tools-x64-Release> .\Valkyria_SDT_TextEditor.exe -mode single -way export -sdt seen0024.sdt -json seen0024.json -code 932
std::exception: ZxArg::Parser::operator[](): arg is empty! -> -sav
```
结果这次连JSON文件都没有了🥲

### 3、尝试使用日区虚拟机运行软件
没变化😌

### 4、尝试使用 `GARbro` 从dat文件中提取sdt文件，然后用 `Valkyria-Tools` 处理sdt文件
还是没变化😌

## 三、最后附上游戏的DAT文件
[DAT+SDT.zip](https://github.com/user-attachments/files/17203771/DAT%2BSDT.zip)
![sticker](https://github.com/user-attachments/assets/5f131468-f288-409e-92a6-05419bccfb24)

**Comment by Dir-A** [comment]
https://github.com/Dir-A/ReVN/releases
用最新的release

**Comment by NooAcc** [comment]
好快的更新，太感动了😭
我决定了，我要把TG里面所有的"D酱名言合集"表情包都收藏起来😋

**Comment by Dir-A** [comment]
![](https://private-user-images.githubusercontent.com/101051650/372435639-5f131468-f288-409e-92a6-05419bccfb24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTExMzQsIm5iZiI6MTcyNzc5MDgzNCwicGF0aCI6Ii8xMDEwNTE2NTAvMzcyNDM1NjM5LTVmMTMxNDY4LWYyODgtNDA5ZS05MmE2LTA1NDE5YmNjZmIyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxMzUzNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmZjNDk1OWQ0M2EyY2RhZDNkYjVmMjU2OGZmYzUwZTM0NTFlYTYzMmRmMjM1YTQwMTdkYTFmMGIwZGFkYjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rPxNQFYXqGhE2PYM1CulDPNmNnM3M66M3II7k6ndm8c)
